In [1]:
import pandas as pd

In [4]:
# The path to our CSV file
gunviolence_file = "/Users/mariaquinton/Desktop/Project-2---Group-E/datasets/gun_violence_data.csv"

# Read our data into pandas
df = pd.read_csv(gunviolence_file)
df.head()

,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,incident_characteristics,latitude,longitude
0,1/1/16,Massachusetts,Boston,0,1,7.0,NaN,NaN,Shot - Wounded/Injured,42.2802,-71.0759
1,1/1/16,Connecticut,Meriden,0,0,5.0,0::Unknown,0::Handgun,Non-Shooting Incident||Car-jacking||Brandishin...,41.5402,-72.7895
2,1/1/16,Missouri,Kansas City,0,1,5.0,NaN,NaN,Shot - Wounded/Injured,39.0979,-94.5221
3,1/1/16,Missouri,Kansas City,0,1,6.0,NaN,NaN,Shot - Wounded/Injured,39.1649,-94.5833
4,1/1/16,Wisconsin,Cudahy,2,0,4.0,0::Unknown,0::Handgun,"Shot - Dead (murder, accidental, suicide)||Sui...",42.9655,-87.8576

In [5]:
df.columns

Index(['date', 'state', 'city_or_county', 'n_killed', 'n_injured',
       'congressional_district', 'gun_stolen', 'gun_type',
       'incident_characteristics', 'latitude', 'longitude'],
      dtype='object')

In [6]:
reduced_gunviolence_df = df.loc[:, ['date', 'state', 'city_or_county', 'n_killed', 'n_injured', 
                                    'gun_stolen', 'gun_type',
       'incident_characteristics', 'latitude', 'longitude']]
reduced_gunviolence_df

,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,latitude,longitude
0,1/1/16,Massachusetts,Boston,0,1,NaN,NaN,Shot - Wounded/Injured,42.2802,-71.0759
1,1/1/16,Connecticut,Meriden,0,0,0::Unknown,0::Handgun,Non-Shooting Incident||Car-jacking||Brandishin...,41.5402,-72.7895
2,1/1/16,Missouri,Kansas City,0,1,NaN,NaN,Shot - Wounded/Injured,39.0979,-94.5221
3,1/1/16,Missouri,Kansas City,0,1,NaN,NaN,Shot - Wounded/Injured,39.1649,-94.5833
4,1/1/16,Wisconsin,Cudahy,2,0,0::Unknown,0::Handgun,"Shot - Dead (murder, accidental, suicide)||Sui...",42.9655,-87.8576
...,...,...,...,...,...,...,...,...,...,...
133961,3/31/18,Louisiana,Rayne,0,0,0::Unknown,0::Unknown,Shots Fired - No Injuries,NaN,NaN
133962,3/31/18,Louisiana,Natchitoches,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",31.7537,-93.0836
133963,3/31/18,Louisiana,Gretna,0,1,0::Unknown,0::Unknown,Shot - Wounded/Injured,29.9239,-90.0442
133964,3/31/18,Texas,Houston,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)",29.7201,-95.6110
133965,3/31/18,Maine,Norridgewock,2,0,0::Unknown||1::Unknown,0::Handgun||1::Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",44.7293,-69.7691

In [7]:
# Rename columns
reduced_gunviolence_df.columns = [
    'date', 'state', 'city_or_county', 'n_killed', 'n_inj', 
    'gun_stolen', 'gun_type','characteristics', 'lat', 'long']

In [8]:
reduced_gunviolence_df.columns

Index(['date', 'state', 'city_or_county', 'n_killed', 'n_inj', 'gun_stolen',
       'gun_type', 'characteristics', 'lat', 'long'],
      dtype='object')

In [11]:
reduced_gunviolence_df.to_csv('/Users/mariaquinton/Desktop/Project-2---Group-E/datasets/reduced_gun_violence.csv')

In [ ]:
reduced_gunviolence_df.to_js('/Users/mariaquinton/Desktop/reduced_gun_violence.js')