In [2]:
import pandas as pd

In [8]:
# The path to our CSV file
gunviolence_file = "datasets/gun_violence_data.csv"

# Read our Kickstarter data into pandas
df = pd.read_csv(gunviolence_file)
df.head()

,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,incident_characteristics,latitude,longitude
0,1/1/13,Pennsylvania,Mckeesport,0,4,14.0,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559
1,1/1/13,California,Hawthorne,1,3,43.0,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330
2,1/1/13,Ohio,Lorain,1,3,9.0,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377
3,1/5/13,Colorado,Aurora,4,0,6.0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020
4,1/7/13,North Carolina,Greensboro,2,2,6.0,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569

In [9]:
df.columns

Index(['date', 'state', 'city_or_county', 'n_killed', 'n_injured',
       'congressional_district', 'gun_stolen', 'gun_type',
       'incident_characteristics', 'latitude', 'longitude'],
      dtype='object')

In [11]:
reduced_gunviolence_df = df.loc[:, ['date', 'state', 'city_or_county', 'n_killed', 'n_injured', 
                                    'gun_stolen', 'gun_type',
       'incident_characteristics', 'latitude', 'longitude']]
reduced_gunviolence_df

,date,state,city_or_county,n_killed,n_injured,gun_stolen,gun_type,incident_characteristics,latitude,longitude
0,1/1/13,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559
1,1/1/13,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330
2,1/1/13,Ohio,Lorain,1,3,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377
3,1/5/13,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020
4,1/7/13,North Carolina,Greensboro,2,2,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569
...,...,...,...,...,...,...,...,...,...,...
239672,3/31/18,Louisiana,Rayne,0,0,0::Unknown,0::Unknown,Shots Fired - No Injuries,NaN,NaN
239673,3/31/18,Louisiana,Natchitoches,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",31.7537,-93.0836
239674,3/31/18,Louisiana,Gretna,0,1,0::Unknown,0::Unknown,Shot - Wounded/Injured,29.9239,-90.0442
239675,3/31/18,Texas,Houston,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)",29.7201,-95.6110
239676,3/31/18,Maine,Norridgewock,2,0,0::Unknown||1::Unknown,0::Handgun||1::Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",44.7293,-69.7691

In [16]:
# Rename columns
reduced_gunviolence_df.columns = [
    'date', 'state', 'city_or_county', 'n_killed', 'n_inj', 
    'gun_stolen', 'gun_type','characteristics', 'lat', 'long']

In [19]:
reduced_gunviolence_df.columns

Index(['date', 'state', 'city_or_county', 'n_killed', 'n_inj', 'gun_stolen',
       'gun_type', 'characteristics', 'lat', 'long'],
      dtype='object')

In [20]:
reduced_gunviolence_df

,date,state,city_or_county,n_killed,n_inj,gun_stolen,gun_type,characteristics,lat,long
0,1/1/13,Pennsylvania,Mckeesport,0,4,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559
1,1/1/13,California,Hawthorne,1,3,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330
2,1/1/13,Ohio,Lorain,1,3,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377
3,1/5/13,Colorado,Aurora,4,0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020
4,1/7/13,North Carolina,Greensboro,2,2,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569
...,...,...,...,...,...,...,...,...,...,...
239672,3/31/18,Louisiana,Rayne,0,0,0::Unknown,0::Unknown,Shots Fired - No Injuries,NaN,NaN
239673,3/31/18,Louisiana,Natchitoches,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)||Ins...",31.7537,-93.0836
239674,3/31/18,Louisiana,Gretna,0,1,0::Unknown,0::Unknown,Shot - Wounded/Injured,29.9239,-90.0442
239675,3/31/18,Texas,Houston,1,0,0::Unknown,0::Unknown,"Shot - Dead (murder, accidental, suicide)",29.7201,-95.6110
239676,3/31/18,Maine,Norridgewock,2,0,0::Unknown||1::Unknown,0::Handgun||1::Shotgun,"Shot - Dead (murder, accidental, suicide)||Sui...",44.7293,-69.7691